name: Publish Website

on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get Latest Code
        uses: actions/checkout@v3

      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1
        with:
          target-server: harborlightfoundation.com
          remote-user: harborlightfoundationcom
          private-ssh-key: ${{ secrets.SSH_KEY }}
          destination-path: /home/harborlightfoundationcom/public_html/wp-content/themes/block-theme
          ssh-port: 6543
